version: '3.8'

networks:
  default:
    name: voi-server-network
    driver: bridge

services:
  voi-server:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    container_name: voi-server-container
    runtime: nvidia
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 32g
    environment:
      - NVIDIA_VISIBLE_DEVICES=0 # limit available GPUs
    ports:
      - "2222:22" # ssh
      - "8765:8765" # server
    volumes:
      - ..:/home/user/voi-server # map the voi-core repo to the container
      - /host/path/to/local/dir:/home/user/.local # map .local and .cache to persist the cache (model weights, etc)
      - /host/path/to/cache/dir:/home/user/.cache
    command: ["/bin/bash", "/home/user/start.sh"]
